=== AyanKushwaha/SAS-Tracking/lib/python/crewlists/schema/crewEmpnoNameSnapshot.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by Steven Laursen (CSC Airline solutions Danmark) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="crewMessage">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="messageName" type="xs:string"/>
				<xs:element name="messageBody">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="crewEmpnoNameSnapshot" type="crewNameEmpnoSnapshot"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="crewNameEmpnoSnapshot">
		<xs:sequence>
			<xs:element name="crew" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="crewId" type="xs:string"/>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="crewEmpnoPeriods">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="crewEmpnoPeriod" type="crewEmpnoPeriod" minOccurs="0" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="version" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="crewEmpnoPeriod">
		<xs:sequence>
			<xs:element name="startDate" type="xs:date"/>
			<xs:element name="endDate" type="xs:date"/>
			<xs:element name="empno" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== AyanKushwaha/SAS-Tracking/lib/python/crewlists/schema/Exampels/CrewEmpnoNameSnapshot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 sp1 (http://www.altova.com)-->
<crewMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\crewEmpnoNameSnapshot.xsd" version="1.00">
	<messageName>CrewEmpnoNameSnapshot</messageName>
	<messageBody>
		<crewEmpnoNameSnapshot version="1.00">
			<crew>
				<crewId>SK  12345</crewId>
				<name>ANDERS HANSEN</name>
				<crewEmpnoPeriods>
					<crewEmpnoPeriod>
						<startDate>1967-08-13</startDate>
						<endDate>1997-08-13</endDate>
						<empno>12345</empno>
					</crewEmpnoPeriod>
					<crewEmpnoPeriod>
						<startDate>1997-08-14</startDate>
						<endDate>2099-08-13</endDate>
						<empno>22345</empno>
					</crewEmpnoPeriod>
				</crewEmpnoPeriods>
			</crew>
			<crew>
				<crewId>SK  34567</crewId>
				<name>JAN SOLBAKKEN</name>
				<crewEmpnoPeriods>
					<crewEmpnoPeriod>
						<startDate>1977-08-13</startDate>
						<endDate>1999-08-13</endDate>
						<empno>String</empno>
					</crewEmpnoPeriod>
					<crewEmpnoPeriod>
						<startDate>1999-08-14</startDate>
						<endDate>2099-08-13</endDate>
						<empno>String</empno>
					</crewEmpnoPeriod>
				</crewEmpnoPeriods>
			</crew>
		</crewEmpnoNameSnapshot>
	</messageBody>
</crewMessage>
