=== AyanKushwaha/SAS-Tracking/lib/python/crewlists/schema/crewVacationTradeSnapshot.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by Steven Laursen (CSC Airline solutions Danmark) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="crewMessage">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="messageName" type="xs:string"/>
				<xs:element name="messageBody">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="crewVacationTradeSnapshot" type="crewVacationTradeSnapshot"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="crewVacationTradeSnapshot">
		<xs:sequence>
			<xs:element name="crew" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="crewId" type="xs:string"/>
						<xs:element name="vacGrps">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="vacGrp" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="name" type="xs:string"/>
												<xs:element name="startDate" type="xs:date"/>
												<xs:element name="endDate" type="xs:date"/>
												<xs:element name="vacActs">
													<xs:complexType>
														<xs:sequence>
															<xs:element name="vacAct" minOccurs="0" maxOccurs="unbounded">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="taskCode" type="xs:string"/>
																		<xs:element name="std" type="xs:dateTime"/>
																		<xs:element name="sta" type="xs:dateTime"/>
																	</xs:sequence>
																</xs:complexType>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="version" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== AyanKushwaha/SAS-Tracking/lib/python/crewlists/schema/Exampels/crewVacationTradeSnapshot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 sp1 (http://www.altova.com)-->
<crewMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../crewVacationTradeSnapshot.xsd" version="1.00">
	<messageName>CrewVacationTradeSnapshot</messageName>
	<messageBody>
		<crewVacationTradeSnapshot version="1.00">
			<crew>
				<crewId>34567</crewId>
				<vacGrps>
					<vacGrp>
						<name>VG12</name>
						<startDate>1967-08-13</startDate>
						<endDate>1997-08-13</endDate>
						<vacActs>
						</vacActs>
					</vacGrp>
					<vacGrp>
						<name>VG34</name>
						<startDate>1997-08-13</startDate>
						<endDate>2099-08-13</endDate>
						<vacActs>
							<vacAct>
								<taskCode>VA</taskCode>
								<std>2005-12-07T23:00:00</std>
								<sta>2005-12-17T23:00:00</sta>
							</vacAct>
							<vacAct>
								<taskCode>VA</taskCode>
								<std>2006-02-14T23:00:00</std>
								<sta>2006-02-17T23:00:00</sta>
							</vacAct>
						</vacActs>
					</vacGrp>
				</vacGrps>
			</crew>
			<crew>
				<crewId>86754</crewId>
				<vacGrps>
					<vacGrp>
						<name>String</name>
						<startDate>1967-08-13</startDate>
						<endDate>2099-08-13</endDate>
						<vacActs>
						</vacActs>
					</vacGrp>
				</vacGrps>
			</crew>
		</crewVacationTradeSnapshot>
	</messageBody>
</crewMessage>
