=== AyanKushwaha/SAS-Tracking/lib/python/crewlists/schema/scheduleUploadCheck.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by Steven Laursen (CSC Airline solutions Danmark) -->
<!-- edited with vim  Pierre-Yves Nielsen (CSC Airline Solutions Denmark) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="scheduleUploadCheck">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="perkey" type="xs:string"/>
				<xs:element name="startDate" type="xs:date"/>
				<xs:element name="endDate" type="xs:date"/>
				<xs:element name="update" type="xs:string"/>
				<xs:element name="activity" type="scheduleActivity" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="scheduleActivity">
		<xs:annotation>
			<xs:documentation>actSeqNo: The activity sequence number</xs:documentation>
			<xs:documentation>stdLocal: The activity's scheduled departure date. Local time, fmt: YYYYMMDD</xs:documentation>
			<xs:documentation>ctd: The activity's corrected time of departure after break. Datetime YYYYMMDD"T"HHMM</xs:documentation>
			<xs:documentation>ctd2: The activity's second corrected time of departure after break. Datetime YYYYMMDD"T"HHMM</xs:documentation>
			<xs:documentation>cta: The activity's corrected time of arrival after break. Datetime YYYYMMDD"T"HHMM</xs:documentation>
			<xs:documentation>std: The activity's scheduled departure. Datetime YYYYMMDD"T"HHMM </xs:documentation>
			<xs:documentation>sta: The activity's scheduled arrival. Datetime YYYYMMDD"T"HHMM </xs:documentation>
			<xs:documentation>stnfr: Departure station for the activity</xs:documentation>
			<xs:documentation>stdto: Arrival station for the activity</xs:documentation>
			<xs:documentation>corrTimeCode: The activity's corrected time code, showing the type of time change</xs:documentation>
			<xs:documentation>activityType: Type of activity, "F": flight, "B": baseactivity</xs:documentation>
			<xs:documentation>activityName: Name of activity, flight or baseactivity, e.g.: "SK 0501", "R13"</xs:documentation>
			<xs:documentation>origDate: Orignal start date for leg in flight, this activity is a part of. Date YYYYMMDD</xs:documentation>
			<xs:documentation>dutyCode: Dutycode for the activity</xs:documentation>
			<xs:documentation>notLast: Indicator. Indicated whether the activity is not the last leg. "1": not last leg</xs:documentation>
			<xs:documentation>legSeqNo: The flight-legs sequence number if the activity is a flight activity otherwise 1</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="actSeqNo" type="xs:integer"/>
			<xs:element name="stdLocal" type="xs:date"/>
			<xs:element name="ctd" type="xs:dateTime"/>
			<xs:element name="cta" type="xs:dateTime"/>
			<xs:element name="ctd2" type="xs:dateTime"/>
			<xs:element name="std" type="xs:dateTime"/>
			<xs:element name="sta" type="xs:dateTime"/>
			<xs:element name="stnfr" type="xs:string"/>
			<xs:element name="stnto" type="xs:string"/>
			<xs:element name="corrTimeCode" type="xs:string"/>
			<xs:element name="activityType">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="F"/>
						<xs:enumeration value="B"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="activityName" type="xs:string"/>
			<xs:element name="origDate" type="xs:date"/>
			<xs:element name="dutyCode" type="xs:string"/>
			<xs:element name="notLast" type="xs:integer"/>
			<xs:element name="legSeqNo" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== AyanKushwaha/SAS-Tracking/lib/python/crewlists/schema/Exampels/scheduleUploadCheckEx.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 sp1 (http://www.altova.com)-->
<scheduleUploadCheck xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Z:\Enterprise model\crew1.6\scheduleUploadCheck.xsd">
	<perkey>SK 10033</perkey>
	<startDate>2007-08-13</startDate>
	<endDate>2007-08-13</endDate>
	<update>Y</update>
	<activity>
		<actSeqNo>-1</actSeqNo>
		<stdLocal>2007-08-13</stdLocal>
		<ctd>2007-08-13T09:30:00Z</ctd>
		<cta>2007-08-13T09:30:00Z</cta>
		<ctd2>2007-08-13T09:30:00Z</ctd2>
		<std>2007-08-13T09:30:00Z</std>
		<sta>2007-08-13T11:30:00Z</sta>
		<stnfr>CPH</stnfr>
		<stnto>LHR</stnto>
		<corrTimeCode> </corrTimeCode>
		<activityType>F</activityType>
		<activityName>SK 501</activityName>
		<origDate>2007-08-13</origDate>
		<dutyCode>L</dutyCode>
		<notLast>-0</notLast>
		<legSeqNo>-1</legSeqNo>
	</activity>
	<activity>
		<actSeqNo>-2</actSeqNo>
		<stdLocal>2007-08-13</stdLocal>
		<ctd>2007-08-13T13:05:00Z</ctd>
		<cta>2007-08-13T15:00:00Z</cta>
		<ctd2>2007-08-13T13:05:00Z</ctd2>
		<std>2007-08-13T13:05:00Z</std>
		<sta>2007-08-13T15:00:00Z</sta>
		<stnfr>LHR</stnfr>
		<stnto>CPH</stnto>
		<corrTimeCode> </corrTimeCode>
		<activityType>F</activityType>
		<activityName>SK 502</activityName>
		<origDate>2007-08-13</origDate>
		<dutyCode>L</dutyCode>
		<notLast>-0</notLast>
		<legSeqNo>-1</legSeqNo>
	</activity>
</scheduleUploadCheck>
